### ISSUE TITLE
MarkBot says live site is not working

### ISSUE THREAD

**Issue by Hath0013** [acgd-webdev-1/image-grid#1]
@thomasjbradley 

All other checks are clear but live site is not working.
Checked local and live sites through MarkBot menu — they both load perfectly. However, when I open the link through here, the page does not load. Downloaded and installed the newest version of MarkBot today.

[http://hath0013.github.io/image-grid/](url)

<img width="791" alt="screen shot 2016-03-29 at 5 52 07 pm" src="https://cloud.githubusercontent.com/assets/16677645/14125030/0361ace4-f5d7-11e5-81eb-cfc1955fa3bc.png">

<img width="585" alt="screen shot 2016-03-29 at 6 02 52 pm" src="https://cloud.githubusercontent.com/assets/16677645/14125311/913f84d6-f5d8-11e5-81fc-4da1d2346461.png">

**Comment by thomasjbradley** [comment]
Do you have version 3.1.0? or 3.1.1?
That's a bug I found in class Monday morning and 3.1.1 fixes it.
The download link in the Canvas message I sent on Sunday will get the newest version, I replaced the file at that location.

**Comment by Hath0013** [comment]
I reinstalled again and it's working now. Thanks!
